name: JFS Woodcraft
favicon: null
layout_spectrum: 0.9731890778057277
typography_spectrum: 0.5108915809541941
title: 'JFS Woodcraft | Custom Reclaimed Goods | Kitchener'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.42541560088284314
  lightness: 0.3737125329207629
  saturation: 0.9821821106597781
  rhythmicContrast: 0.7673525505233556
purpose: []
