name: JFS Woodcraft
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'JFS Woodcraft | Custom Reclaimed Goods | Kitchener'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1b1b'
    - '#cacaca'
    - '#525252'
    - '#808080'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.7673525505233556
purpose: []
