name: JFS Woodcraft
favicon: null
layout_spectrum: 0.48452
typography_spectrum: 0.0959
title: 'JFS Woodcraft | Custom Reclaimed Goods | Kitchener'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1b1b'
    - '#cacaca'
    - '#525252'
    - '#808080'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
